# Based on https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml

sudo: false
language: php

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

hosts:
  - publishpress.localhost

env:
  global:
    - SITE_URL="http://publishpress.localhost"
    - SITE_DOMAIN="publishpress.localhost"
    - DB_NAME="test"
    - PLUGIN_SLUG="publishpress"

install:
  - composer install --no-dev --prefer-dist

matrix:
  include:
    - php: '7.1'
      env: WP_VERSION=latest
    - php: '7.1'
      env: WP_VERSION=master
    - php: '7.1'
      env: WP_VERSION=4.8
    - php: '5.6'
      env: WP_VERSION=master
    - php: '5.6'
      env: WP_VERSION=4.8
    - php: '5.4'
      env: WP_VERSION=master
    - php: '5.4'
      env: WP_VERSION=4.8
  allow_failures:
    - env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

notifications:
  slack:
    secure: Is16b7yl3I1k0Yul3xaBtCPhUoM7V9qOefNFN8RF8k7aDVsG4/nRaaOglgcW1GA4/AyfXK1DmiV/qFd5hQuSmyeujMeMnnNhD+8xoSy25LpkoC0WJ+16JzeH3DesSHCY5g2ujBBmdaisuAhg5T3uVkRaoAiXhcjLjIAJRFdMFy+pcwj2EhCKisShEsrymh5wsCbHsdm9ewzZUoa9Un9z1s5PgPlkwoWblD+NccE9hsLCUIj5szVealxg5yLFtEnAeCX9k1v0tWPfZpHZajr2tXN0FeBx/gsxFGC3Krx5dS9vI+ydPUJnEZgJwMGrCaNryLdhz8E4K4hv+878Xc5FgLl2kMaKQcmFFXcVCY7Ljuw2vVw68YOvickheQjKcuFUoqPjby9g3Q0rtW/lseev9A+u44my2o78af357cGolPHqCtrWgZwcsJDPUL00JfNkeikcn30jRAK4KUwFRdB3eDyZYhEajhALQK+Nn4Iw3mMJPSh6AMmg+vAQZWxw7E5hESfP4RUTzOlejHSMRoTQjwI9gNsxD5SGkjOfdhV0L3TasqpmRP1HmLxVXiXMB24eQ5nuxe++K7F18EYFkCK9eyI57EEbQe1VdjuoPQG6l+Btebff9EXhnMA8k/iQ6UCS8BfeK1d3oZjzo2O1J5AYvSw7LQPYJKI+Cfd9cGz+NG8=
