codecov:
  branch: master
  bot: OSTraining
  ci: travis-ci.com
  notify:
    after_n_builds: null
    countdown: null
    require_ci_to_pass: yes
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"
        only_pulls: null
        message: null
        flags: null
        paths: null

  fixes: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
  flags: null
  paths: null
